SELECT n.n_name AS nation_name, COUNT(DISTINCT c.c_custkey) AS number_of_customers, SUM(o.o_totalprice) AS total_sales, AVG(o.o_totalprice) AS average_order_value, COUNT(DISTINCT o.o_orderkey) AS number_of_orders FROM nation AS n JOIN customer AS c ON n.n_nationkey = c.c_nationkey JOIN orders AS o ON c.c_custkey = o.o_custkey WHERE n.n_regionkey IN (1, 4, 0, 2, 3) AND n.n_name = 'FRANCE' AND o.o_orderdate BETWEEN '1995-01-01' AND '1996-12-31' GROUP BY n.n_name ORDER BY total_sales DESC;
SELECT n.n_name AS nation, COUNT(DISTINCT s.s_suppkey) AS number_of_suppliers, AVG(l.l_discount) AS average_discount, SUM(l.l_extendedprice * (1 - l.l_discount)) AS total_revenue FROM supplier s JOIN nation n ON s.s_nationkey = n.n_nationkey JOIN partsupp ps ON s.s_suppkey = ps.ps_suppkey JOIN lineitem l ON ps.ps_partkey = l.l_partkey AND ps.ps_suppkey = l.l_suppkey JOIN orders o ON l.l_orderkey = o.o_orderkey WHERE l.l_shipdate >= '1994-01-01' AND l.l_shipdate < '1995-01-01' GROUP BY n.n_name ORDER BY total_revenue DESC, n.n_name;
SELECT n.n_name AS nation, AVG(s.s_acctbal) AS average_account_balance, COUNT(DISTINCT s.s_suppkey) AS number_of_suppliers, SUM(ps.ps_availqty) AS total_available_quantity, SUM(ps.ps_supplycost * ps.ps_availqty) AS total_supply_cost FROM nation AS n JOIN supplier AS s ON n.n_nationkey = s.s_nationkey JOIN partsupp AS ps ON s.s_suppkey = ps.ps_suppkey JOIN part AS p ON ps.ps_partkey = p.p_partkey WHERE p.p_size IN (5, 26) AND ps.ps_comment LIKE '%final%' AND s.s_phone IN ('10-235-972-1443', '18-693-682-4752', '10-146-485-1160') AND p.p_name LIKE '%lavender%' GROUP BY n.n_name ORDER BY total_supply_cost DESC, average_account_balance DESC;
SELECT r.r_name AS region_name, COUNT(DISTINCT p.p_partkey) AS number_of_parts, AVG(p.p_retailprice) AS average_retail_price, SUM(ps.ps_availqty) AS total_available_quantity, SUM(ps.ps_supplycost) AS total_supply_cost, AVG(ps.ps_supplycost) AS average_supply_cost FROM region r JOIN partsupp ps ON ps.ps_partkey = ps.ps_partkey JOIN part p ON p.p_partkey = ps.ps_partkey GROUP BY r.r_name ORDER BY total_supply_cost DESC;
SELECT r_name AS region, n_name AS nation, COUNT(DISTINCT s_suppkey) AS number_of_suppliers, AVG(s_acctbal) AS average_account_balance, SUM(ps_availqty) AS total_available_quantity, AVG(ps_supplycost) AS average_supply_cost FROM region JOIN nation ON n_regionkey = r_regionkey JOIN supplier ON s_nationkey = n_nationkey JOIN partsupp ON s_suppkey = ps_suppkey WHERE n_nationkey IN (8, 11, 4) AND n_name IN ('IRAN', 'ETHIOPIA') GROUP BY r_name, n_name ORDER BY average_account_balance DESC, total_available_quantity DESC;
SELECT r_name AS region, n_name AS nation, COUNT(DISTINCT s_suppkey) AS supplier_count, COUNT(DISTINCT c_custkey) AS customer_count, AVG(s_acctbal) AS avg_supplier_acctbal, AVG(c_acctbal) AS avg_customer_acctbal, SUM(l_extendedprice * (1 - l_discount)) AS total_revenue FROM region JOIN nation ON n_regionkey = r_regionkey JOIN supplier ON s_nationkey = n_nationkey JOIN customer ON c_nationkey = n_nationkey JOIN orders ON o_custkey = c_custkey JOIN lineitem ON l_orderkey = o_orderkey WHERE l_shipdate >= '1992-01-01' AND l_shipdate < '1993-01-01' AND l_returnflag = 'N' GROUP BY region, nation ORDER BY total_revenue DESC, region, nation LIMIT 10;
SELECT r.r_name AS region_name, COUNT(DISTINCT s.s_suppkey) AS total_suppliers, COUNT(DISTINCT o.o_orderkey) AS total_orders, AVG(o.o_totalprice) AS avg_order_total_price, SUM(li.l_quantity) AS total_quantity_supplied FROM supplier s JOIN partsupp ps ON s.s_suppkey = ps.ps_suppkey JOIN lineitem li ON ps.ps_partkey = li.l_partkey AND ps.ps_suppkey = li.l_suppkey JOIN orders o ON li.l_orderkey = o.o_orderkey JOIN customer c ON o.o_custkey = c.c_custkey JOIN region r ON c.c_nationkey = s.s_nationkey WHERE s.s_acctbal > 0 GROUP BY r.r_name ORDER BY total_quantity_supplied DESC, avg_order_total_price DESC;
SELECT r_name AS region, n_name AS nation, COUNT(DISTINCT c_custkey) AS customer_count, SUM(o_totalprice) AS total_sales, AVG(s_acctbal) AS avg_supplier_balance, AVG(c_acctbal) AS avg_customer_balance FROM region JOIN nation ON r_regionkey = n_regionkey JOIN customer ON n_nationkey = c_nationkey JOIN orders ON c_custkey = o_custkey JOIN supplier ON n_nationkey = s_nationkey WHERE o_orderdate BETWEEN DATE '2022-01-01' AND DATE '2022-12-31' AND c_mktsegment = 'BUILDING' GROUP BY region, nation ORDER BY total_sales DESC, avg_supplier_balance DESC;
SELECT r.r_name AS region_name, AVG(ps.ps_availqty) AS average_available_quantity, SUM(ps.ps_supplycost) AS total_supply_cost, COUNT(DISTINCT s.s_suppkey) AS number_of_suppliers, COUNT(DISTINCT n.n_nationkey) AS number_of_nations FROM region r JOIN nation n ON r.r_regionkey = n.n_regionkey JOIN supplier s ON n.n_nationkey = s.s_nationkey JOIN partsupp ps ON s.s_suppkey = ps.ps_suppkey GROUP BY r.r_name ORDER BY total_supply_cost DESC;
